### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ghost** [rust3ds/ctru-rs-old#3]
People cannot use or modify your project without violating copyright laws due to the lack of a license. Please add an open-source license to this project.

See: https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by HybridEidolon** [comment]
Ahh yes, I haven't maintained this in a while but I'll put a license on it. I hadn't gotten any real progress done so I didn't expect others to use it.

**Comment by ghost** [comment]
Thank you!
