### ISSUE TITLE
Error during compilation

### ISSUE THREAD

**Issue by hallucino** [rust3ds/ctru-rs-old#53]
I'm getting the following error with ctru-rs via rust3ds-template:
error[E0200]: the trait `core::ops::Place<V>` requires an `unsafe impl` declaration
    --> /home/XX/.cargo/git/checkouts/ctru-rs-1206856f7a5d76bc/bf6ef66/ctr-std/src/collections/hash/map.rs:1975:1
     |
1975 | / impl<'a, K, V> Place<V> for EntryPlace<'a, K, V> {
1976 | |     fn pointer(&mut self) -> *mut V {
1977 | |         self.bucket.read_mut().1
1978 | |     }
1979 | | }
     | |_^

error: aborting due to previous error

error: Could not compile `std`.

My version:
X@anonymous:~/3DS/rust3ds-template$ rustc -V
rustc 1.25.0-nightly (9fd7da904 2018-01-25)
X@anonymous:~/3DS/rust3ds-template$ xargo -V
xargo 0.3.10
cargo 0.26.0-nightly (91e36aa86 2018-01-25)

**Comment by FenrirWolf** [comment]
Nightly churn strikes again.

Just merged a fix, try compiling again and it should work. You might have to manually clear out the old sysroot though. `rm -rf ~/.xargo/lib/rustlib/3ds` should do the trick

Thanks for the heads-up!

**Comment by hallucino** [comment]
Thx ! I will test that

**Comment by hallucino** [comment]
Seems ok for this now. Thx
