### ISSUE TITLE
QUERTY instead of QWERTY

### ISSUE THREAD

**Issue by anyputer** [rust3ds/ctru-rs-old#76]
There is no such thing as a QUERTY keyboard, it's supposed to be QWERTY.
There are 5 occurrences of Querty in https://github.com/rust3ds/ctru-rs/blob/master/ctru-rs/src/applets/swkbd.rs where it's supposed to be Qwerty! :/

**Comment by FenrirWolf** [comment]
Well then. That's a pretty silly goof on my part, but also an easy one to fix. I'll get on that later today.

**Comment by anyputer** [comment]
Not every occurrence is fixed, though.

**Comment by linouxis9** [comment]
Will check, thank you @hyarsan !

**Comment by FenrirWolf** [comment]
Hah, guess I double-goofed then. Fortunately that is also easily fixable assuming I actually pay full attention on the next attempt =P

**Comment by FenrirWolf** [comment]
I pushed https://github.com/rust3ds/ctru-rs/commit/6070ddb0330f3e87e583e23dd1f8df521b394d26 which should actually for realsies fix this unless I am somehow ultra blind.

**Comment by linouxis9** [comment]
We can always check by grepping for Querty in the whole repository?
