### ISSUE TITLE
Is possible to use any crates.io library?

### ISSUE THREAD

**Issue by kurai021** [rust3ds/ctru-rs-old#79]
Noob question :/

I want to use some libraries (and maybe UI if possible), but I don't know how can I find 3DS (or the target specs) compatible libraries in crates.io

**Comment by FenrirWolf** [comment]
This project makes a best-effort attempt at replicating `std`, so if a library only depends on things from `std` then it's likely to work. However, lots of projects out there depend on platform-specific behavior and/or bindings to C code, and none of that code is aware of the 3DS as a platform so they're unlikely to work. That includes things like UI crates, unfortunately.

**Comment by kurai021** [comment]
Thank you for your response, since Rust is not what I am looking to do homebrew with a UI, what alternatives would I have?
