### ISSUE TITLE
Should bindings be based on ctrulib 1.1 or the latest github versions?

### ISSUE THREAD

**Issue by FenrirWolf** [rust3ds/ctru-rs-old#8]
Up until now I've been going under the assumption that we should target ctrulib 1.1, since that's the current default you get when installing devkitARM. But there have been a number of interesting changes to ctrulib as of late, such as support for the official 3DS software keyboard and changes to other services like APT and FS. I've been experimenting with binding the FS service in particular, and the recent changes help make it slightly less of a confusing mess than the 1.1 version was.

Of course, the main drawback to this idea would be that there have been no release versions of ctrulib since 1.1, so telling users to get the "latest ctrulib" is somewhat ambiguous until such a time as 1.2 releases. ~~And as far as I can tell, there is no indication of an official 1.2 release any time soon.~~ EDIT: Guess there might be a 1.2 sometime this month or the next.

**Comment by HybridEidolon** [comment]
What we could do is just build ctrulib as part of a build script. That way the only version used is exclusively the one that the wrapper is compatible with.

**Comment by FenrirWolf** [comment]
1.2 is finally out, so let's just use that.
